# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-14 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20180614_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='installed_apps',
            field=models.TextField(default='messenger:/mainMessages,gmail:https://gmail.com,setitlaer,calculator,contacts:/contacts,appstore/appstore'),
        ),
    ]
