# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-14 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20180614_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
