# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-15 02:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0006_auto_20180614_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
