# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-15 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_app_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
